name: Node CI Workflow

on:
  pull_request:
    branches:
      - main # main branch에서 PR할 때마다 이벤트 트리거
  push:
    branches:
      - main # merge 되기 전 테스트 수행

defaults:
  run:
    shell: bash
    working-directory: ./ # 이어지는 Job들은 ./ 디렉토리에서 수행됨

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
