name: Node CI Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./ # 이어지는 Job들은 ./ 디렉토리에서 수행됨

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
